// Strapi-style ORM accessor: `<obj>.db.query(MODEL_UID).<orm_method>(...)`.
// MODEL_UID is a literal model identifier (not raw SQL); the trailing
// findOne/findMany/create/update/delete/count are intrinsically
// parameterised — the actual SQL is generated by the ORM and per-call
// values arrive through field-keyed object literals the driver escapes.
//
// FP-guard: cfg-unguarded-sink and taint-unsanitised-flow must NOT
// fire on this shape.

declare const strapi: any;

async function getApiToken(whereParams: Record<string, unknown>) {
    return strapi.db.query('admin::api-token').findOne({
        select: ['id', 'name', 'lastUsedAt'],
        populate: ['permissions'],
        where: whereParams,
    });
}

async function listTokens() {
    return strapi.db.query('admin::api-token').findMany({
        where: { type: 'read-only' },
    });
}

async function createToken(data: unknown) {
    return strapi.db.query('admin::api-token').create({ data });
}

async function updateToken(id: number, data: unknown) {
    return strapi.db.query('admin::api-token').update({ where: { id }, data });
}

async function deleteToken(id: number) {
    return strapi.db.query('admin::api-token').delete({ where: { id } });
}

async function countTokens() {
    return strapi.db.query('admin::api-token').count();
}
